### PR TITLE
Fix SVG render mirroring

### PR DESCRIPTION
**Pull request by TriAnMan**
This fix makes SVG code to be rendered correctly.
Without this fix `qrcode.js` produces SVG image in "mirrored" way. Some of qr-code scanners can't handle such code. E.g.: [`Scanvi` for `iOS`](http://scanvi.com/)

### CODE REVIEW

**Comment by jozan** [comment]
NeoReader on Android and Windows Phone's native reader didn't recognise any QR codes without this fix.

**Comment by ashelley** [comment]
+1 on this fix.  thanks @TriAnMan and thanks @davidshimjs 

This fixes the SVG mirroring issues that makes it so that QR Code Reader for android works with svg rendering.

https://play.google.com/store/apps/details?id=me.scan.android.client&hl=en

**Comment by gitbreaker222** [comment]
@TriAnMan I guess this can be closed, as it may seem that this change was merged here: https://github.com/davidshimjs/qrcodejs/pull/44/files

**Comment by TriAnMan** [comment]
@gitbreaker222 Thanks.

**Pull request closed without merging**
